
package com.suu.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PayerRecptService", targetNamespace = "http://server.suu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PayerRecptService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnValue", targetNamespace = "http://server.suu.com/", className = "com.suu.client.ReturnValue")
    @ResponseWrapper(localName = "returnValueResponse", targetNamespace = "http://server.suu.com/", className = "com.suu.client.ReturnValueResponse")
    @Action(input = "http://server.suu.com/PayerRecptService/returnValueRequest", output = "http://server.suu.com/PayerRecptService/returnValueResponse")
    public String returnValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
