
package com.suu.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PayerRecptServiceService", targetNamespace = "http://server.suu.com/", wsdlLocation = "http://localhost:9099/procPayorPayment?wsdl")
public class PayerRecptServiceService
    extends Service
{

    private final static URL PAYERRECPTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYERRECPTSERVICESERVICE_EXCEPTION;
    private final static QName PAYERRECPTSERVICESERVICE_QNAME = new QName("http://server.suu.com/", "PayerRecptServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9099/procPayorPayment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYERRECPTSERVICESERVICE_WSDL_LOCATION = url;
        PAYERRECPTSERVICESERVICE_EXCEPTION = e;
    }

    public PayerRecptServiceService() {
        super(__getWsdlLocation(), PAYERRECPTSERVICESERVICE_QNAME);
    }

    public PayerRecptServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYERRECPTSERVICESERVICE_QNAME, features);
    }

    public PayerRecptServiceService(URL wsdlLocation) {
        super(wsdlLocation, PAYERRECPTSERVICESERVICE_QNAME);
    }

    public PayerRecptServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYERRECPTSERVICESERVICE_QNAME, features);
    }

    public PayerRecptServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayerRecptServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PayerRecptService
     */
    @WebEndpoint(name = "PayerRecptServicePort")
    public PayerRecptService getPayerRecptServicePort() {
        return super.getPort(new QName("http://server.suu.com/", "PayerRecptServicePort"), PayerRecptService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayerRecptService
     */
    @WebEndpoint(name = "PayerRecptServicePort")
    public PayerRecptService getPayerRecptServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.suu.com/", "PayerRecptServicePort"), PayerRecptService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYERRECPTSERVICESERVICE_EXCEPTION!= null) {
            throw PAYERRECPTSERVICESERVICE_EXCEPTION;
        }
        return PAYERRECPTSERVICESERVICE_WSDL_LOCATION;
    }

}
